site_name: Stuffbox

theme:
  name: material
  nav_style: dark
  logo: logo.png
  favicon: logo.png
  palette:
    scheme: default

markdown_extensions:
  - attr_list
  - md_in_html

#markdown_extensions:
#    - toc:
#        toc_depth : "1-1"
plugins: []
